### ISSUE TITLE
Manga title text output

### ISSUE THREAD

**Issue by weiw11** [MarvNC/mangadex-list-exporter#2]
Is the manga title suppose to contain `<![CDATA[`MANGA TITLE`]]>` on the output?

Image:
![image](https://user-images.githubusercontent.com/62213594/95411788-6639b600-08f5-11eb-8cfc-2cff03dadd37.png)

**Comment by MarvNC** [comment]
It's intended. I wasn't too sure what it meant at first when looking at the MyAnimeList export while writing the script, but it seemed to be useful for preventing issues with the xml so I kept it. Further reading: [stackoverflow](https://stackoverflow.com/questions/2784183/what-does-cdata-in-xml-mean).

**Comment by weiw11** [comment]
Oh that makes sense. I guess it's easy to remove manually and doesn't really show up unless you view it with a text editor like I did.

Also I think you should use praseDouble instead of parseInt on the chapter as there are some chapters that increments by decimals.
`let chapter = Number.parseInt(ratings.childNodes[3].childNodes[1].innerHTML);`

**Comment by MarvNC** [comment]
Yeah, I'd use excel for viewing the exported xmls. I chose to parse them as int because MangaDex numbering isn't really consistent anyway, and because list sites like MAL and AL only count whole numbers. Side chapters are supposed to be added to the chapter count as well, so the chapter count is mismatched between sites anyway.
